### ISSUE TITLE
Add Packages.xz

### ISSUE THREAD

**Issue by Patrik-svobodik** [Shugabuga/Silica#1]
Simply make the script create Packages.xz file for faster loading and less 404 spamming

**Comment by Shugabuga** [comment]
I just ran `apt update` and don't see any 404 spamming. Do you have a screenshot of the 404ing?

I am not opposed to adding this, but I may want to get rid of all the 404s that appear if that's the case.

**Comment by Patrik-svobodik** [comment]
Sileo checks for Packages.xz first, that is why I said 404 spamming, it only tries other packages.* after it 404’s

**Comment by Shugabuga** [comment]
Ah, okay. I'm going to quickly verify this with Sileo Team and add a gzip call to compress the file in 1.1.0.

**Comment by Shugabuga** [comment]
Added in 1.1.0.
