### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by willbraffman** [Shugabuga/Silica#12]
The changelog will not work. Below I have included one of my index.json that I have been adding to, even tho it will not show. I have also included the .json file for the corresponding tweak from the docs folder. If you need more just let me know. Thanks in advance!!
[com.willbraff.historyofios.json.zip](https://github.com/Shugabuga/Silica/files/3270064/com.willbraff.historyofios.json.zip)

[index.json.zip](https://github.com/Shugabuga/Silica/files/3270060/index.json.zip)

**Comment by absidue** [comment]
You need to use correct json to get the changelog to work. At the moment you have a dictionary as the changelog, but you should have an array of dictionaries.
What you have:
```javascript
"changelog": {
    "version": "1.1",
    "changes": "fix",
    "version": "1.2",
    "changes": "added iOS 6 icons",
    "version": "1.2.1",
    "changes": "added classic extentions",
    "version": "1.3",
    "changes": "added docks",
    "version": "1.3.1",
    "changes": "fix docks",
    "version": "1.3.2",
    "changes": "fix docks iOS 10&Below",
    "version": "1.4",
    "changes": "added iOS 13 icons."
}
```
How it should be:
```javascript
"changelog": [
    {
        "version": "1.1",
        "changes": "fix"
    },
    {
        "version": "1.2",
        "changes": "added iOS 6 icons"
    },
    {
        "version": "1.2.1",
        "changes": "added classic extentions"
    },
    {
        "version": "1.3",
        "changes": "added docks"
    },
    {
        "version": "1.3.1",
        "changes": "fix docks"
    },
    {
        "version": "1.3.2",
        "changes": "fix docks iOS 10&Below"
    },
    {
        "version": "1.4",
        "changes": "added iOS 13 icons."
    }
]
```

**Comment by Shugabuga** [comment]
@absidue Thank you for taking your time to find out the issue. I'm sorry I wasn't able to! 😦

@willbraffman As @absidue said, try making sure the changelog object is an array.

Using your file, change this...

```json
"changelog": {
    "version": "1.4",
    "changes": "added iOS 13 icons."
  }
```

...to this...

```json
"changelog": [
    {
        "version": "1.4",
        "changes": "added iOS 13 icons."
    }
]
```

If this doesn't work, let me know.

**Comment by Sparoney** [comment]
Hijacking this, is there a way to make the changelog multiline? Or a way to parse HTML code?

**Comment by Shugabuga** [comment]
As of now, no @sparoney.

**Comment by Shugabuga** [comment]
Closed due to inactivity. Feel free to re-open this if the posted solution doesn't work @willbraffman.

**Comment by absidue** [comment]
@Sparoney insert `\n` where you would like new lines; it works best with lists.

example: `- Line 1\n- Line 2`

outputs: 
- Line 1
- Line 2
