### ISSUE TITLE
How do I get rid of this CNAME error?

### ISSUE THREAD

**Issue by neumaif02** [Shugabuga/Silica#14]
The page build completed successfully, but returned the following warning for the `master` branch:

You cannot use CNAMEs ending with github.io or github.com. Instead, create a repository named neumaif02.github.io. See https://help.github.com/articles/setting-up-your-pages-site-repository/

For information on troubleshooting Jekyll see:

 https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by Shugabuga** [comment]
You can safely ignore it, and I may try to fix this next build (whenever I get a chance). Alternatively, just delete the generated CNAME file in the /docs/ folder.

**Comment by neumaif02** [comment]
It annoys me to get an error via email every time I commit changes.

**Comment by Shugabuga** [comment]
Properly fixed in latest commit.
