### ISSUE TITLE
Error by running index.py

### ISSUE THREAD

**Issue by neumaif02** [Shugabuga/Silica#15]
`All done! Please look over the generated "index.json" file and consider populating the "silica_data" folder with a description, screenshots, and an icon.
Traceback (most recent call last):
  File "index.py", line 226, in <module>
    main()
  File "index.py", line 51, in main
    DebianPackager.CheckForSilicaData()
  File "/home/nepeta/Schreibtisch/Nepeta/util/DebianPackager.py", line 394, in CheckForSilicaData
    os.remove(self.root + "Packages/" + folder + "/silica_data/scripts/Control")
FileNotFoundError: [Errno 2] No such file or directory: '/home/nepeta/Schreibtisch/Nepeta/util/../Packages/Cuboid/silica_data/scripts/Control'
`

**Comment by Shugabuga** [comment]
What is in Silica's `Packages` folder?

**Comment by neumaif02** [comment]
[silica_data.zip](https://github.com/Shugabuga/Silica/files/3667547/silica_data.zip)

**Comment by neumaif02** [comment]
A lot of packages.

**Comment by neumaif02** [comment]
[Cuboid.zip](https://github.com/Shugabuga/Silica/files/3667618/Cuboid.zip)

**Comment by neumaif02** [comment]
The solution is to just rename the `control` file to `Control`, but I got a different error.

**Comment by Shugabuga** [comment]
The error Python gives is misleading. You don't need a `Control` file for Silica. Silica uses its own JSON file format to deal with what the Control files does.

You need to put an `index.json` file in the `silica_data` folder. See the README for details. This replaces the `Control` file. This will include the package name, version, and more. Trying to provide your own Control file in the `scripts` folder will break Silica.

If you just have the DEBs, you can just drop them into the `Packages` file and Silica will attempt to automatically convert them into a Silica-readable format and generate the needed `.json` file from user input and the information inside the DEB.
