### ISSUE TITLE
Cannot run Setup.sh

### ISSUE THREAD

**Issue by ajaidan** [Shugabuga/Silica#26]
When I run setup.sh, I get the following output:

File "/home/ajaidan/Silica/setup.sh", line 2
    echo "Silica Configuration Utility"
                                      ^
SyntaxError: invalid syntax

**Comment by Shugabuga** [comment]
Are you running this in WSL? If so, it's because of line breaks and you need to use `git clone` *within* WSL to properly run Silica's setup.

**Comment by ajaidan** [comment]
Hi - yes, i am in WSL but I ran git clone.

**Comment by Shugabuga** [comment]
Did you do so within the WSL shell?

**Comment by ajaidan** [comment]
Yes

**Comment by ajaidan** [comment]
I guess I was doing something wrong, because now everything is working. Thanks for your effort!

**Comment by Shugabuga** [comment]
Glad to hear! If you figure out what you did, let me know and I'll make a note of it in the README.
