### ISSUE TITLE
Multiple errors when running $ python3 index.py

### ISSUE THREAD

**Issue by kid1carus** [Shugabuga/Silica#4]
**_1) See attached image for first error received.  The index.json file was malformatted.  Issues with file were corrected._** 

![FIRST ERROR](https://user-images.githubusercontent.com/45052773/57585312-82dd7e80-74b4-11e9-9c08-ecbda6b6b68e.png)

**_2)Ran index.py cmd again and got the following error:_**
Silica Compiler 1.0.0 Traceback (most recent call last): File "index.py", line 214, in <module> main() File "index.py", line 54, in main reposettings = PackageLister.GetRepoSettings() File "/Users/kid1carus/Silica/util/PackageLister.py", line 124, in GetRepoSettings return json.load(content_file) File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/init.py", line 296, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/init_.py", line 348, in loads return _default_decoder.decode(s) File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 21 column 1 (char 536)

**_Problem was with the file at Styles/settings.json.  Corrected the problem and ran python3 index.py again.

3)Received error:_**
 File "index.py", line 214, in <module>
    main()
  File "index.py", line 114, in main
    index_html = DepictionGenerator.RenderIndexHTML()
  File "/Users/kid1carus/Silica/util/DepictionGenerator.py", line 288, in RenderIndexHTML
    replacements = DepictionGenerator.RenderDataHTML(self)
  File "/Users/kid1carus/Silica/util/DepictionGenerator.py", line 329, in RenderDataHTML
    data['repo_packages'] = DepictionGenerator.PackageEntryList(self, tweak_release)
  File "/Users/kid1carus/Silica/util/DepictionGenerator.py", line 444, in PackageEntryList
    list_el += DepictionGenerator.PackageEntry(self, package['name'], package['developer']['name'],
TypeError: string indices must be integers

_**CURRENTLY WAITING FOR FIX**_

**Comment by wbraffman** [comment]
hi, I have the same issue, and Shuga is currently fixing it, should come shortly. It happens for me when I try a recently updated yourepo package

**Comment by Shugabuga** [comment]
@wbraffman Your error is unrelated to this issue.

@kid1carus Points 1 and 2 were due to JSON errors, an error that will be clarified in 1.0.1.

**Comment by wbraffman** [comment]
Ah, sorry my mistake

**Comment by Shugabuga** [comment]
@kid1carus #1 and #2 now have descriptive errors to describe the issue.

**Comment by Shugabuga** [comment]
There were two issues, both which were user error:

1. You can't delete image assets from Styles. You should replace them, but deleting the icon.png and the Generic folder breaks Silica.
2. Your settings.json was still malformatted. Use this instead:

```json
{
    "name": "Angel Land",
    "description": "Awesome & beautiful iOS themes",
    "tint": "#28ABF5",
    "cname": "http://kid1carus.github.io ",
    "maintainer": {
        "name": "kid1carus",
        "email": "kid1carus.1mages@gmail.com"
    },
    "automatic_git": "true"
}
```

I'll try to add more descriptive error messages, but I'm closing this as Resolved. Thank you for sending me your Silica install; these two changes got your repo to compile on my machine.
