### ISSUE TITLE
Errors by running index.py

### ISSUE THREAD

**Issue by neumaif02** [Shugabuga/Silica#7]
`Traceback (most recent call last):
  File "index.py", line 226, in <module>
    main()
  File "index.py", line 133, in main
    PackageLister.CreateFile("docs/depiction/web/" + tweak_data['bundle_id'] + ".html", tweak_html)
  File "/home/silica/Schreibtisch/Silica/util/PackageLister.py", line 24, in CreateFile
    with open(self.root + path, "w") as text_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/silica/Schreibtisch/Silica/util/../docs/depiction/web/io/jailbreak.github.neumaif02.meinerstestheme.html'
`

**Comment by Shugabuga** [comment]
What OS are you running on, and can I see the contents of the file at `/home/felix/Schreibtisch/Silica-master/Packages/*/silica_data/index.json` (the asterisk being the folder containing the package)?

**Comment by neumaif02** [comment]
I use Linux Mint Cinnamon
https://drive.google.com/open?id=1MgrN2t1C3YIkBZ0aFe2KQdHubgvf3C85

**Comment by neumaif02** [comment]
Can you please help me?

**Comment by Shugabuga** [comment]
Once I have the time and motivation, yes.

**Comment by neumaif02** [comment]
I need this, but okay.

**Comment by neumaif02** [comment]
When do you have time and motivation?

**Comment by neumaif02** [comment]
Fixed it by changing the bundle id in index.json.

**Comment by Shugabuga** [comment]
What was the old Bundle ID?

**Comment by neumaif02** [comment]
io/jailbreak/.github.neumaif02.felixjailbreaktweaks

Von meinem iPhone gesendet

**Comment by Shugabuga** [comment]
Yeah, those slashes probably broke it.

**Comment by neumaif02** [comment]
I also got this error all the time:

The page build completed successfully, but returned the following warning
for the `master` branch:

The CNAME `neumaif02.github.io/jailbreak/`
<http://neumaif02.github.io/jailbreak/>is not properly formatted. See
https://help.github.com/articles/troubleshooting-custom-domains/#github-repository-setup-errors
for
more information.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

Shuga <notifications@github.com> schrieb am So. 1. Sep. 2019 um 01:50:

**Comment by Shugabuga** [comment]
Remove the `/jailbreak/` in the `"cname"` property of the `settings.json` file and set the `"subfolder"` property to `"jailbreak"` in the same file..

**Comment by neumaif02** [comment]
So neumaif02.github.io/ ./jailbreak?

Von meinem iPhone gesendet

**Comment by Shugabuga** [comment]
No slashes or periods are needed for either.

**Comment by neumaif02** [comment]
Is this right?

Shuga <notifications@github.com> schrieb am Mi., 4. Sep. 2019, 06:27:

**Comment by Shugabuga** [comment]
neumaif02.github.io

jailbreak
