### ISSUE TITLE
Automatically update pre/postinst when updating a DEB.

### ISSUE THREAD

**Issue by Samgisaninja** [Shugabuga/Silica#9]
If you have multiple versions of the same package, the deb that Silica builds for the docs folder uses the newest version’s contents, ~~but the oldest postinst script.~~

EDIT: I can’t figure out how to change the issue title, but I was wrong, it doesn’t use the oldest version’s scripts, it uses the scripts in the silica_data folder. These scripts should be updated when the package is updated.

**Comment by Samgisaninja** [comment]
`rm Packages/<package id>/silica_data/scripts/*`

**Comment by Shugabuga** [comment]
Updated the title for you.

**Comment by Shugabuga** [comment]
Added in 1.1.0.
